### ISSUE TITLE
Add link to ready-to-use docker image

### ISSUE THREAD

**Issue by mirkolenz** [bufbuild/connect-envoy-demo#1]
Dear Buf team,
first of all I want to thank you for all the effort you put into the gRPC/Protobuf ecosystem!

With the help of the example provided in this repo, I created a project that provides a ready-to-use proxy server via a Docker image: https://github.com/mirkolenz/grpc-proxy

I would like to ask if you could consider adding a link to my repo in the README of this demo. The goal of my project is to make using the required envoy proxy easier and I think it could benefit from a bit more visibility.

I can totally understand if you do not want to link to a third-party repo. In this case, feel free to close this issue.

Keep up your great work!

**Comment by timostamm** [comment]
Hey Mirko, the Docker image looks super useful to me :+1: We are not ready yet to add links to third parties, but we will likely have a good place to do so at some point. I've taken a note to make sure your repo will be on it.

**Comment by mirkolenz** [comment]
Hi Timo, thanks for the kind words and also the PR, keep up your great work at buf!
